spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/isolatebg?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Sofia"
    username: root
    password: 12345
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 25MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
isolate:
  remember.me.key: 1234
  base-url: https://isolate.bg
logging:
  level:
    #    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: INFO
    org.springframework.security: INFO
    #    org.thymeleaf: DEBUG
    org.springframework.web: INFO
#    org.apache.coyote.http11.Http11Processor: DEBUG
#    org.apache.tomcat.util.net: DEBUG

server:
    port: 8182
mailjet:
  api-key: d0cb9d673684e8903e80cd019fe714ba
  secret-key: 66e93f44ba6b2b1dded0b7aa2c2e7947
  from-email: info@stcnc.eu
  from-name: StCNC


